<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CoinHiveCaptcha\CoinHiveCaptcha'                => __DIR__.'/src/CoinHiveCaptcha/CoinHiveCaptcha.php',
    'CoinHiveCaptcha\Service\CoinHiveCaptchaService' => __DIR__.'/src/CoinHiveCaptcha/Service/CoinHiveCaptchaService.php',
    'CoinHiveCaptcha\Helper\CoinHiveCaptchaHelper'   => __DIR__.'/src/CoinHiveCaptcha/Helper/CoinHiveCaptchaHelper.php',
    'CoinHiveCaptcha\Module'                         => __DIR__.'/Module.php',
);
